#!/bin/csh -f

# Restore files to their correct state to get timestamps
unzip -o -q ../LAMPS_CODE.zip
chmod +w -R LAMPS_SRC

# Delete some junk
rm LAMPS_SRC/CONVERT/I2DLG/SRC/JNCTEX.F_JMC
rm LAMPS_SRC/CONVERT/I2DXF/SRC/IFF_POLY.BCK
rm LAMPS_SRC/CONVERT/IFF2SIF/SRC/TEXT.SRC_JMC
rm LAMPS_SRC/FLOWLINE/LIBRARY/SRC/FLN_INIT.RFO
rm LAMPS_SRC/IMP/IPATCH/SRC/EDIT_MH.OLD_SRC
rm LAMPS_SRC/IMP/IPATCH/SRC/PRINT_MH.OLD_SRC
rm LAMPS_SRC/IMP/IPATCH/SRC/READ_MH.OLD_SRC
rm LAMPS_SRC/IMP/IPATCH/SRC/TYPE_MH.OLD_SRC
rm LAMPS_SRC/LSLMAINT/OSMHLIB/OSMH_NEW/OSMH_NEW_INI
rm LAMPS_SRC/MATRIX/DTIVIEW/SRC/MODEL_OLD.SRC
rm LAMPS_SRC/POLYGONS/IPOLYGON/SRC/CHECK_COVER_LABEL.OLD_SRC
rm FLOWLINE/COM/FLOWLINEINI.COM_OLD
rm DTMPREPARE/RIV3D/SRC/OLDCHKBOX.SRC
rm DTMPREPARE/RIV3D/SRC/OLDNODHGTS.SRC

rm -f no_copyright
foreach file ( `find LAMPS_SRC -type f` )
 switch ( $file:e )
 case 'SRC':
 case 'CMN':
 case 'FOR':
 case 'F':
 case 'PAR':
  set comments='C'
  set commentb='C '
  set commente='C'
  breaksw;
 case 'C':
 case 'H':
  set comments='/*'
  set commentb=' '
  set commente=' */'
  breaksw;
 case 'COM':
  set comments='$!'
  set commentb='$! '
  set commente='$!'
  breaksw;
 case 'MAR':
 case 'MAC':
  set comments=';'
  set commentb='; '
  set commente=';'
  breaksw;
 case 'CLD':
  set comments='!'
  set commentb='! '
  set commente='!'
  breaksw;
 casde 'PAS':
  set comments='(*'
  set commentb=' '
  set commente=' *)'
  breaksw;
 default:
  echo $file:e >> no_copyright
#  echo $file " : " $file:e
  continue
  breaksw;
 endsw

 echo "$comments" >tmp
 sed -e "s/^/$commentb/" -e 's/$/\r/' >>tmp <<END_MSG
* This file is part of the LAMPS distribution, released as a software
* preservation project to archive digital history for future historians.
* Copyright (c) 1980-2002 Laser-Scan Ltd, 1Spatial Group Ltd
*
END_MSG
 stat $file |sed -n -e "s/Modify/$commentb* Timestamp of this file for the 2002 release was/p" |sed -e 's/$/\r/' >>tmp
 sed -e "s/^/$commentb/" -e 's/$/\r/' >>tmp <<END_REST_OF_MESSAGE
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, version 3.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see http://www.gnu.org/licenses/.
END_REST_OF_MESSAGE
 echo "$commente" >>tmp
cat $file >> tmp
mv tmp $file
end

git add LAMPS_SRC

git commit -m 'Add copyright messages.'

cat no_copyright|sort |uniq -c |sort -n
rm no_copyright
