
/************************************************************************/
/*									*/
/*			CBC.H						*/
/*									*/
/*	Preset values for IFF Control Bytes				*/
/*									*/
/*	GJR, NUTIS			11/8/88				*/
/*	JB				25/5/89				*/
/*									*/
/************************************************************************/

#define NF 'N'+256*'F'
#define FS 'F'+256*'S'
#define TH 'T'+256*'H'
#define ST 'S'+256*'T'
#define EF 'E'+256*'F'
#define NS 'N'+256*'S'
#define CC 'C'+256*'C'
#define CP 'C'+256*'P'
#define TC 'T'+256*'C'
#define CH 'C'+256*'H'
#define EO 'E'+256*'O'
#define EJ 'E'+256*'J'
#define VO 'V'+256*'O'
#define SS 'S'+256*'S'
#define SL 'S'+256*'L'
#define TX 'T'+256*'X'
#define RA 'R'+256*'A'
#define NO 'N'+256*'O'
#define MD 'M'+256*'D'
#define EM 'E'+256*'M'
#define MH 'M'+256*'H'
#define RO 'R'+256*'O'
#define JB 'J'+256*'B'
#define JP 'J'+256*'P'
#define SH 'S'+256*'H'
#define CS 'C'+256*'S'
#define AC 'A'+256*'C'
#define ZS 'Z'+256*'S'
#define HI 'H'+256*'I'
#define CB 'C'+256*'B'
#define TS 'T'+256*'S'

