/************************************************************************/
/*									*/
/* Copyright Laser-Scan Laboratories Ltd, Cambridge CB4 4FY, England	*/
/* Author    J Barber   18-May-1989					*/
/*									*/
/*		     C M D L I N E . H					*/
/*									*/
/* Header file for command line qualifiers for I2ARC			*/
/*									*/
/************************************************************************/ 

extern BOOLEAN  had_frt;	/* TRUE if we had FRT file qualifier	*/
extern BOOLEAN  had_log;	/* TRUE if we log file open/close, etc	*/
extern BOOLEAN	had_debug;	/* TRUE if we should output debug info	*/

