#define I2ARC__NORMAL                  	   240418825
#define I2ARC__ARCNAM                  	   240418834
#define I2ARC__ARCOPNERR               	   240418842
#define I2ARC__CMDLNERR                	   240418850
#define I2ARC__FRTOPNERR               	   240418858
#define I2ARC__IFFOPNERR               	   240418866
#define I2ARC__NOFRTENTRY              	   240418874
#define I2ARC__TMPFILERR               	   240418882
