/*
 * This file is part of the LAMPS distribution, released as a software
 * preservation project to archive digital history for future historians.
 * Copyright (c) 1980-2002 Laser-Scan Ltd, 1Spatial Group Ltd
 *
 * Timestamp of this file for the 2002 release was: 1993-04-21 16:07:58.000000000 +0100
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 */
#define I2ARC__NORMAL                  	   240418825
#define I2ARC__LINEINPAR               	   240418835
#define I2ARC__BADATTCODE              	   240418840
#define I2ARC__BADATTNAME              	   240418848
#define I2ARC__DEFAULTACD              	   240418856
#define I2ARC__MISSATTDEF              	   240418864
#define I2ARC__NOATTNAME               	   240418872
#define I2ARC__NOTEXT                  	   240418880
#define I2ARC__OUTFIL                  	   240418888
#define I2ARC__UNKCMD                  	   240418896
#define I2ARC__ARCNAM                  	   240418906
#define I2ARC__ARCOPNERR               	   240418914
#define I2ARC__CMDLNERR                	   240418922
#define I2ARC__ERRCLO                  	   240418930
#define I2ARC__ERROPN                  	   240418938
#define I2ARC__ERRRDPAR                	   240418946
#define I2ARC__FRTOPNERR               	   240418954
#define I2ARC__PAROPNERR               	   240418962
#define I2ARC__IFFOPNERR               	   240418970
#define I2ARC__NOFRTENTRY              	   240418978
#define I2ARC__TMPFILERR               	   240418986
