
! IMP_GUIDE.SPEC
! specification for the IMP user guide manual

auto_title
title		IMP
title		User_ Guide
issue		3.2
short_title	IMP GUIDE
category	User
author		S Townrow
date		21-Jun-1991

changes
contents
index

! The next three commands are strictly redundant, as they describe the
! default situation. However, they should be included as they make it
! more obvious what is going on.

no_section_numbers
auto_name_chapter
flag_page

Chapter		INTRODUCTION	INTRODUCTION
Chapter		MODULES		MODULE DESCRIPTIONS
