/*
 * This file is part of the LAMPS distribution, released as a software
 * preservation project to archive digital history for future historians.
 * Copyright (c) 1980-2002 Laser-Scan Ltd, 1Spatial Group Ltd
 *
 * Timestamp of this file for the 2002 release was: 1989-09-18 12:19:10.000000000 +0100
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 */

/************************************************************************/
/*									*/
/*			CBC.H						*/
/*									*/
/*	Preset values for IFF Control Bytes				*/
/*									*/
/*	JB				15/9/89				*/
/*									*/
/************************************************************************/

#define NF 'N'+256*'F'
#define FS 'F'+256*'S'
#define TH 'T'+256*'H'
#define ST 'S'+256*'T'
#define EF 'E'+256*'F'
#define NS 'N'+256*'S'
#define CC 'C'+256*'C'
#define CP 'C'+256*'P'
#define TC 'T'+256*'C'
#define CH 'C'+256*'H'
#define EO 'E'+256*'O'
#define EJ 'E'+256*'J'
#define VO 'V'+256*'O'
#define SS 'S'+256*'S'
#define SL 'S'+256*'L'
#define TX 'T'+256*'X'
#define RA 'R'+256*'A'
#define NO 'N'+256*'O'
#define MD 'M'+256*'D'
#define EM 'E'+256*'M'
#define MH 'M'+256*'H'
#define RO 'R'+256*'O'
#define JB 'J'+256*'B'
#define JP 'J'+256*'P'
#define SH 'S'+256*'H'
#define CS 'C'+256*'S'
#define AC 'A'+256*'C'
#define ZS 'Z'+256*'S'
#define HI 'H'+256*'I'
#define CB 'C'+256*'B'
#define TS 'T'+256*'S'

