/*
 * This file is part of the LAMPS distribution, released as a software
 * preservation project to archive digital history for future historians.
 * Copyright (c) 1980-2002 Laser-Scan Ltd, 1Spatial Group Ltd
 *
 * Timestamp of this file for the 2002 release was: 1990-06-14 10:11:10.000000000 +0100
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 */
/************************************************************************/
/*									*/
/* Copyright Laser-Scan Laboratories Ltd, Cambridge CB4 4FY, England	*/
/* Author    J Barber   18-May-1989					*/
/*									*/
/*		     C M D L I N E . H					*/
/*									*/
/* Header file for command line qualifiers for I2GDB			*/
/*									*/
/************************************************************************/ 

extern BOOLEAN  had_frt;	/* TRUE if we had FRT file qualifier	*/
extern BOOLEAN  had_log;	/* TRUE if we log file open/close, etc	*/
extern BOOLEAN	had_debug;	/* TRUE if we should output debug info	*/
extern BOOLEAN 	had_param;	/* TRUE if we had PARAMETERS file qualifier */
