#!/usr/bin/python 
#Filename: lamps_images_index_html.py
#
# Python Script to create html index to LAMPS screenshots and other images
#
# Created PGH 2019-04-13
# Modified PGH 2019-05-02 (for pdf)
# modified PGH 2020-02-19 (for images)

import os, string, re, sys, time, datetime

def main():
	"Script to create html index for Laser-Scan LAMPS images"
	outhtmlfilename = "../lamps_images_index.html"
	try:
		outhtmlfile = open(outhtmlfilename, 'w')  
	except IOError:
		print("Can\'t open output html file for writing. "+outhtmlfilename)
		sys.exit(0)
        outhtmlfile.write("<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 3.2 Final//EN"">\n")
	outhtmlfile.write("<HTML><HEAD><TITLE>VMS LAMPS Software images index</TITLE>\n")
	outhtmlfile.write("<LINK rel=""stylesheet"" type=""text/css"" href=""lamps.css""></HEAD>\n")
	outhtmlfile.write("<H1>VMS LAMPS Software Screenshots and Similar Images Index</H1>\n")
	outhtmlfile.write("This is an automatically generated index to screenshots and other images of the VMS LAMPS digital mapping software suite.\n")
	outhtmlfile.write("These were archived from the original Laser-Scan VMS system software run under VAX emulation on a SimH simulator by Paul Hardy in 2018-2020.\n")
	outhtmlfile.write("See also the <A HREF=""index.html"">index overview</A> for LAMPS source and documentation files.\n")
#
	rootDir = '../../LAMPS_IMAGES'
	for dirName, subdirList, fileList in os.walk(rootDir):
#		print('Found directory: %s' % dirName)
		level = dirName.count(chr(92))
#		print('Level = %d' % level)
		if level==1:
			package = dirName.rsplit(chr(92),1)[1]
			print("LAMPS software package " + package)
			outhtmlfile.write("<H2>LAMPS software package " + package + "</H2>\n")
		elif level==2:
			component = dirName.rsplit(chr(92),1)[1]
			print("LAMPS software package " + package + " component " + component)
			outhtmlfile.write("<H3>LAMPS software package " + package + " component " + component + "</H3>\n")
		elif level>2:
			subfolder = dirName.rsplit(chr(92),1)[1]
			print("LAMPS software package " + package + " component " + component + ", subfolder " + subfolder)
			outhtmlfile.write("<H4>Subfolder " + subfolder + "</H4>\n")
		for fname in fileList:
			fullpath=dirName+'\\'+fname
			modified = os.path.getmtime(fullpath)
			modtime = time.strftime("%d-%b-%Y",time.localtime(modified))
			relpath = fullpath.replace('../../', '../')
			if fname.endswith(('.PNG', '.png')):
#				print('\t%s is a LAMPS image file, modified %s' % (fname, modtime))
				outhtmlfile.write(fname + ' is a LAMPS image (<A href="' + relpath + '">download</A>) on ' + modtime + '<BR>\n')
	outhtmlfile.write("<p><hr><a href=""index.html"">Go up to LAMPS archive index overview</a></BODY></HTML>\n")
	outhtmlfile.write("<P><I>Generated by lamps_image_index.py</BR>\n")
	return

# #Start point for script
main()

# All done.


