/*
 * This file is part of the LAMPS distribution, released as a software
 * preservation project to archive digital history for future historians.
 * Copyright (c) 1980-2002 Laser-Scan Ltd, 1Spatial Group Ltd
 *
 * Timestamp of this file for the 2002 release was: 1988-06-10 12:22:08.000000000 +0100
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 */
#define LSL__CREATED                   	   201424905
#define LSL__NORMAL                    	   201424913
#define LSL__SIGSUCC                   	   201424921
#define LSL__STREOL                    	   201424929
#define LSL__STRCHAR                   	   201424937
#define LSL__STRCMD                    	   201424945
#define LSL__STRSPACE                  	   201424953
#define LSL__DUMMY1                    	   201424961
#define LSL__DUMMY2                    	   201424969
#define LSL__DUMMY3                    	   201424977
#define LSL__DUMMY4                    	   201424985
#define LSL__DUMMY5                    	   201424993
#define LSL__DUMMY6                    	   201425001
#define LSL__DUMMY7                    	   201425009
#define LSL__DUMMY8                    	   201425017
#define LSL__DUMMY9                    	   201425025
#define LSL__DUMMY10                   	   201425033
#define LSL__DEFTOOBIG                 	   201425040
#define LSL__EOF                       	   201425048
#define LSL__FILTOOLONG                	   201425056
#define LSL__NEGPOSNMK                 	   201425064
#define LSL__POSNMKOVF                 	   201425072
#define LSL__RANREV                    	   201425080
#define LSL__RECTOOBIG                 	   201425088
#define LSL__SIGWARN                   	   201425096
#define LSL__SRCTOOBIG                 	   201425104
#define LSL__NOFIELD                   	   201425112
#define LSL__DUMMYW2                   	   201425120
#define LSL__DUMMYW3                   	   201425128
#define LSL__DUMMYW4                   	   201425136
#define LSL__DUMMYW5                   	   201425144
#define LSL__DUMMYW6                   	   201425152
#define LSL__DUMMYW7                   	   201425160
#define LSL__DUMMYW8                   	   201425168
#define LSL__DUMMYW9                   	   201425176
#define LSL__DUMMYW10                  	   201425184
#define LSL__AMBIG                     	   201425194
#define LSL__AMBINEQ                   	   201425202
#define LSL__AMBIG2                    	   201425210
#define LSL__BADEXCEP                  	   201425218
#define LSL__BADINEQ                   	   201425226
#define LSL__BADPARSE                  	   201425234
#define LSL__BADTCOND                  	   201425242
#define LSL__BASECH                    	   201425250
#define LSL__BUFOVFLW                  	   201425258
#define LSL__BUFFEROVF                 	   201425266
#define LSL__COMMA                     	   201425274
#define LSL__DEFFILNAM                 	   201425282
#define LSL__DEFVERNUM                 	   201425290
#define LSL__DEVALLOC                  	   201425298
#define LSL__ENDOFTAPE                 	   201425306
#define LSL__ENDOFVOL                  	   201425314
#define LSL__FAC                       	   201425322
#define LSL__FILINUSE                  	   201425330
#define LSL__FLTDIV                    	   201425338
#define LSL__FLTOVF                    	   201425346
#define LSL__FLTUND                    	   201425354
#define LSL__HADEXCP                   	   201425362
#define LSL__ILLEGLUN                  	   201425370
#define LSL__INTPARSERR                	   201425378
#define LSL__INTDIV                    	   201425386
#define LSL__INTOVF                    	   201425394
#define LSL__INVALSPEC                 	   201425402
#define LSL__LUNINUSE                  	   201425410
#define LSL__MAXPAREX                  	   201425418
#define LSL__MISSARGS                  	   201425426
#define LSL__MSGNOTFND                 	   201425434
#define LSL__NOLUNS                    	   201425442
#define LSL__NONUM                     	   201425450
#define LSL__NOSUCHDEV                 	   201425458
#define LSL__NOSUCHLUN                 	   201425466
#define LSL__NOSUCHFILE                	   201425474
#define LSL__RESPARSOVF                	   201425482
#define LSL__SIGERR                    	   201425490
#define LSL__SRCFILNAM                 	   201425498
#define LSL__SRCVERNUM                 	   201425506
#define LSL__STRTOOLONG                	   201425514
#define LSL__SYNTAXERR                 	   201425522
#define LSL__SYSCLOSE                  	   201425530
#define LSL__SYSERR                    	   201425538
#define LSL__SYSFIND                   	   201425546
#define LSL__SYSREAD                   	   201425554
#define LSL__SYSREW                    	   201425562
#define LSL__SYSUPD                    	   201425570
#define LSL__SYSWRITE                  	   201425578
#define LSL__SYSOPEN                   	   201425586
#define LSL__UNEXPCH                   	   201425594
#define LSL__UNEXPCMD                  	   201425602
#define LSL__UNEXPCMD2                 	   201425610
#define LSL__UNEXPEOF                  	   201425618
#define LSL__UNEXPEOL                  	   201425626
#define LSL__FILNOLEN                  	   201425634
#define LSL__SYSFLUSH                  	   201425642
#define LSL__DUMMYE3                   	   201425650
#define LSL__DUMMYE4                   	   201425658
#define LSL__DUMMYE5                   	   201425666
#define LSL__DUMMYE6                   	   201425674
#define LSL__DUMMYE7                   	   201425682
#define LSL__DUMMYE8                   	   201425690
#define LSL__DUMMYE9                   	   201425698
#define LSL__DUMMYE10                  	   201425706
#define LSL__SIGSEVER                  	   201425716
#define LSL__DUMMYS1                   	   201425724
#define LSL__DUMMYS2                   	   201425732
#define LSL__DUMMYS3                   	   201425740
#define LSL__DUMMYS4                   	   201425748
#define LSL__DUMMYS5                   	   201425756
#define LSL__DUMMYS6                   	   201425764
#define LSL__DUMMYS7                   	   201425772
#define LSL__DUMMYS8                   	   201425780
#define LSL__DUMMYS9                   	   201425788
#define LSL__DUMMYS10                  	   201425796
#define LSL__SIGINFO                   	   201425803
#define LSL__DUMMYI1                   	   201425811
#define LSL__DUMMYI2                   	   201425819
#define LSL__DUMMYI3                   	   201425827
#define LSL__DUMMYI4                   	   201425835
#define LSL__DUMMYI5                   	   201425843
#define LSL__DUMMYI6                   	   201425851
#define LSL__DUMMYI7                   	   201425859
#define LSL__DUMMYI8                   	   201425867
#define LSL__DUMMYI9                   	   201425875
#define LSL__DUMMYI10                  	   201425883
#define LSL__IFFOPENED                 	   201425891
#define LSL__IFFPARSE                  	   201425898
#define LSL__IFFVERNUM                 	   201425906
#define LSL__IFFSIZE                   	   201425914
#define LSL__IFFOPEN                   	   201425922
#define LSL__IFFCREATE                 	   201425930
#define LSL__IFFMODIFY                 	   201425938
#define LSL__LCMOPNOUT                 	   201425947
#define LSL__LOGOPNOUT                 	   201425955
#define LSL__OPLCM                     	   201425962
#define LSL__OPLOG                     	   201425970
#define LSL__IFFINREV                  	   201425978
#define LSL__IFFOUTREV                 	   201425986
